Call remote webhooks on ballot success/failure
promethe42/cocorico pull request #55
Opened 2016-10-07 10:07 UTC by yaubi

Changes:
  - App model gets a new webhookURL field.
  - After each ballot attempt, successful or not, a message is appended to the webhook queue.
  - An always-running worker consumes webhook messages and, for each of them, call the remote URL.
  - Failing webhooks are retried every minute for 24 hours.

Known problems:
  - The worker does not reconnect to RabbitMQ in case of dropped connection.
  - Webhooks are called one after the other due to RabbitMQ channels being synchronous.
  - The retry mechanism is extremely costly, due to:
      - messages being checked for their retry TTL continuously and
      - messages needing to be parsed/serialised from/to JSON each time.
  - The retry mechanism is pretty basic. Instead the retry delay could:
      - grow over time,
      - differ depending on HTTP error.

2016-10-08 09:43 UTC, promethe42 commented
> The retry mechanism is extremely costly

So no DLX yet?

2016-10-08 20:49 UTC, yaubi commented
Not yet. I wanted to have a working base first. I started a POC using DLX today, but I am not done yet.

2016-10-09 09:47 UTC, promethe42 commented
> Not yet. I wanted to have a working base first. I started a POC using DLX today, but I am not done yet.

OK great.

Take a look at `/api/test` and `/script/run-tests.sh` to implement tests too.

2016-10-12 06:28 UTC, JMLX42 requested changes
- We need a documentation page (like [this one](https://github.com/promethe42/cocorico/blob/master/doc/External_Users.md)) to explain the webhook mechanism and format.
- The event _must_ be a JWT signed with the App.secret.

2016-10-17 20:21 UTC, merged